version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bungalov-app
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - Iyzipay__ApiKey=${IYZIPAY_API_KEY}
      - Iyzipay__SecretKey=${IYZIPAY_SECRET_KEY}
      - Iyzipay__BaseUrl=https://sandbox-api.iyzipay.com
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:8080"

volumes:
  mssql_data:
